### ISSUE TITLE
Installing .deb fails due to missing zst compression.

### ISSUE THREAD

**Issue by tasselru** [billkenney/qidi_3series_recovery#1]
A big thank you for providing this script, it worked great to finally restore my Smart3. There was a small issue along the way though. The version of dpkg that comes with the "smart-20230322.img" image is apparently too old to unpack zst compressed files. So when running the script, dpkg is unable to decompress and install the supplied .deb file. Installing zstd and repacking the .deb according to the method in Quique's answer here did the trick: https://unix.stackexchange.com/questions/669004/zst-compression-not-supported-by-apt-dpkg

**Comment by billkenney** [comment]
> A big thank you for providing this script, it worked great to finally restore my Smart3. There was a small issue along the way though. The version of dpkg that comes with the "smart-20230322.img" image is apparently too old to unpack zst compressed files. So when running the script, dpkg is unable to decompress and install the supplied .deb file. Installing zstd and repacking the .deb according to the method in Quique's answer here did the trick: https://unix.stackexchange.com/questions/669004/zst-compression-not-supported-by-apt-dpkg 

I think you're the first one to try with the smart3. I'm glad it worked and I appreciate the feedback. I uploaded a repackaged version with xz compression to the repo. If you wouldn't mind confirming that it installs without the compression error, I can close the issue: `wget --no-check-certificate https://raw.githubusercontent.com/billkenney/qidi_3series_recovery/main/mksclient-smart3.deb ; sudo dpkg -i mksclient-smart3.deb`
